#postgres:
#  image: postgres:10.3
#  environment:
#    POSTGRES_USER: blog
#    POSTGRES_PASSWORD: blog
#    POSTGRES_DB: blog
#  ports:
#    - "3306"
app:
  build: .
#  links:
#    - postgres
  volumes:
     - .:/usr/src/app
  ports:
    - "8888:8888"
#  command: --db_host=postgres
